SELECT apellido1, apellido2, nombre FROM persona WHERE tipo = 'alumno' ORDER BY apellido1, apellido2, nombre;
SELECT nombre, apellido1, apellido2 FROM persona WHERE tipo = 'alumno' AND telefono IS NULL;
SELECT * FROM persona WHERE tipo = 'alumno' AND YEAR(fecha_nacimiento) = 1999;
SELECT * FROM persona WHERE tipo = 'profesor' AND telefono IS NULL AND nif LIKE '%K';
SELECT * FROM asignatura WHERE cuatrimestre = 1 AND curso = 3 AND id_grado = 7;
SELECT persona.apellido1, persona.apellido2, persona.nombre, departamento.nombre FROM persona INNER JOIN profesor ON persona.id = profesor.id_profesor INNER JOIN departamento ON profesor.id_departamento = departamento.id ORDER BY persona.apellido1, persona.apellido2, persona.nombre;
SELECT asignatura.nombre, curso_escolar.anyo_inicio, curso_escolar.anyo_fin FROM persona INNER JOIN alumno_se_matricula_asignatura ON persona.id = alumno_se_matricula_asignatura.id_alumno INNER JOIN asignatura ON alumno_se_matricula_asignatura.id_asignatura = asignatura.id INNER JOIN curso_escolar ON alumno_se_matricula_asignatura.id_curso_escolar = curso_escolar.id WHERE persona.nif = '26902806M';
SELECT departamento.nombre FROM departamento  INNER JOIN profesor ON profesor.id_departamento = departamento.id WHERE grado.nombre = 'Enginyeria informatica(Pla 2015)';
SELECT * FROM persona INNER JOIN persona ON alumno_se_matricula_asignatura.id_alumno = persona.id WHERE tipo = 'alumno' AND curso_escolar.anyo_inicio = 2018;
SELECT departamento.nombre, persona.apellido1, persona.apellido2, persona.nombre FROM persona INNER JOIN profesor ON persona.id = profesor.id_profesor LEFT JOIN departamento ON profesor.id_departamento = departamento.id ORDER BY departamento.nombre, persona.apellido1, persona.apellido2, persona.nombre;
SELECT * FROM persona WHERE persona.tipo = 'profesor' AND NOT EXISTS (SELECT * FROM profesor WHERE persona.id = profesor.id_profesor);
SELECT * FROM departamento WHERE id NOT IN (SELECT id_departamento FROM profesor);
SELECT * FROM profesor INNER JOIN persona ON profesor.id_profesor = persona.id WHERE profesor.id_profesor NOT IN (SELECT id_profesor FROM asignatura WHERE id_profesor IS NOT NULL);
SELECT * FROM asignatura WHERE NOT EXISTS (SELECT * FROM profesor WHERE profesor.id_profesor = asignatura.id_profesor);
SELECT departamento.* FROM departamento INNER JOIN profesor ON departamento.id = profesor.id_departamento WHERE NOT EXISTS (SELECT * FROM asignatura WHERE profesor.id_profesor = asignatura.id_profesor);
SELECT COUNT(*) FROM persona WHERE tipo = 'alumno';
SELECT COUNT(*) FROM persona WHERE tipo = 'alumno' AND YEAR(fecha_nacimiento) = 1999;
SELECT departamento.nombre, COUNT(profesor.id_profesor) FROM departamento INNER JOIN profesor ON departamento.id = profesor.id_departamento GROUP BY departamento.id ORDER BY 2 DESC;
SELECT departamento.nombre, COUNT(profesor.id_profesor) FROM departamento LEFT JOIN profesor ON departamento.id = profesor.id_departamento GROUP BY departamento.id ORDER BY 2 DESC;
SELECT grado.nombre, COUNT(asignatura.id) FROM grado LEFT JOIN asignatura ON grado.id = asignatura.id_grado GROUP BY grado.id ORDER BY COUNT(asignatura.id) DESC;
SELECT grado.nombre, COUNT(asignatura.id) FROM grado LEFT JOIN asignatura ON grado.id = asignatura.id_grado GROUP BY grado.id HAVING COUNT(asignatura.id) > 40;
SELECT grado.nombre, asignatura.tipo, SUM(asignatura.creditos) FROM grado INNER JOIN asignatura ON grado.id = asignatura.id_grado GROUP BY grado.id, asignatura.tipo;
SELECT curso_escolar.anyo_inicio, COUNT(DISTINCT persona.id) FROM curso_escolar INNER JOIN alumno_se_matricula_asignatura ON curso_escolar.id = alumno_se_matricula_asignatura.id_curso_escolar INNER JOIN persona ON alumno_se_matricula_asignatura.id_alumno = persona.id GROUP BY curso_escolar.id ORDER BY 1 DESC;
SELECT profesor.id_profesor, persona.nombre, persona.apellido1, persona.apellido2, COUNT(asignatura.id) FROM profesor INNER JOIN persona ON profesor.id_profesor = persona.id LEFT JOIN asignatura ON profesor.id_profesor = asignatura.id_profesor GROUP BY profesor.id_profesor ORDER BY 5 DESC;
SELECT * FROM persona WHERE tipo = 'alumno' AND fecha_nacimiento = (SELECT MAX(fecha_nacimiento) FROM persona WHERE tipo = 'alumno');
SELECT * FROM persona WHERE persona.tipo = 'profesor' AND NOT EXISTS (SELECT * FROM profesor WHERE persona.id = profesor.id_profesor);
SELECT * FROM departamento WHERE id NOT IN (SELECT id_departamento FROM profesor);
SELECT * FROM profesor INNER JOIN persona ON profesor.id_profesor = persona.id WHERE profesor.id_profesor NOT IN (SELECT id_profesor FROM asignatura WHERE id_profesor IS NOT NULL);
SELECT * FROM asignatura WHERE NOT EXISTS (SELECT * FROM profesor WHERE profesor.id_profesor = asignatura.id_profesor);
SELECT departamento.* FROM departamento INNER JOIN profesor ON departamento.id = profesor.id_departamento WHERE NOT EXISTS (SELECT * FROM asignatura WHERE profesor.id_profesor = asignatura.id_profesor);